### ISSUE TITLE
jkt_subdistrict_boundary

### ISSUE THREAD

**Issue by ilpise** [smart-facility/cognicity-schema#2]
Hello, I've installed the cognicity-server.
When I go to the Map link on the web interface I got an error about the jkt_subdistrict_boundary table.
` error: dataQuery: Database query failed, relation "jkt_subdistrict_boundary" does not exist`
I've searched inside the .sql files in cognicity-schema and the creation of this table is not present.

The .sql inside the aggregates directory return other errors related to other tables 
The `cat aggregate_reports_schema.sql | psql -d cognicity` works but the
`cat aggregate_reports.sql | psql -d cognicity` return
`ERROR:  relation "jkt_rw_boundary" does not exist`

the ` cat get_sum_count_aggregates.sql | psql -d cognicity` return
`ERROR:  relation "jkt_rw_boundary" does not exist`
and the `cat get_sum_count_aggregates_json.sql | psql -d cognicity` return
`ERROR:  relation "jkt_rw_boundary" does not exist`

Thank you.

**Comment by talltom** [comment]
Hi @ilpise this is because the boundary tables are "data" as opposed to empty "schema". I think the best solution is to include these in this repo under a "sample data" folder. I will update this repo and documentation shortly.

Thanks

**Comment by matthewberryman** [comment]
@talltom:
1. If you can identify which tables you want I can export them and put them here in github.
2. We will need to add the appropriate CC licence in for the data. See [here](https://github.com/idleberg/Creative-Commons-Markdown) for markdown formatted ones of English, we may wish to generate a markdown one for Bahasa Indonesia using the [html version](http://creativecommons.org/licenses/by-nc/4.0/legalcode.id) to replace the text. I am not sure about the schema files and licensing.

**Comment by ilpise** [comment]
Dear all,
is not possible just to have the not existent tables structure this way the data can be eventually filled with imaginary "boundaries" but the platform can at least works for development.
Thank you so much.

**Comment by talltom** [comment]
Hi @ilpise - that was my thinking too, but as you're trying to build [petajakarta-web](http://github.com/smart-facility/petajakarta-web) I think it would be less frutstrating for yourself and other users to have samples of the data required to get this working. I have now updated the README.md to the schema repo with further details. Both @matthewberryman and myself are out of office today, but we'll get these data up as soon as possible.

@matthewberryman taking you up on the above offer, could you take a look at the updated README.md, and add a sample_data folder with SQL files for the city boundaries and hydro-infrastructure tables? Probably using `INSERT` statements is easiest?

**Comment by talltom** [comment]
@ilpise in the meantime, you could potentially change the cognicity-server config to point at different polygon data, though this may cause more problems...

See lines 84 - 94 of `config.js` in [cognicity-server](https://github.com/smart-facility/cognicity-server/blob/master/config.js)

**Comment by matthewberryman** [comment]
@ilpise I have added .sql files for the sample data in the [sample_data directory](https://github.com/smart-facility/cognicity-schema/tree/master/sample_data). I made these using `pg_dump` so they will create the table and then `COPY` commands, rather than `INSERT` as @talltom suggested. Please note the licences for the various sample data files as per [README.md](https://github.com/smart-facility/cognicity-schema/blob/master/README.md).

**Comment by ilpise** [comment]
Thank you all,
now the map is working correctly.
