### ISSUE TITLE
No documentation about aggregates

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/cognicity-schema#3]
Are these needed?
If so, when do they need to be loaded—I guess after the main schema, and before sample data?
In what order do they need to be loaded—I guess the [aggregates schema](https://github.com/smart-facility/cognicity-schema/blob/master/aggregates/aggregate_reports_schema.sql) comes before the rest, but do the rest need to be in any particular order? Could we not merge these, given they're not data?

Note that these issues apply equally to master and 2.0.x, so don't forget to merge and commit and push both.

**Comment by talltom** [comment]
Matthew, these are old development files, used for 1.0.x development. These queries are now encapsulated by cognicity-server and/or the schema in both master and 2.0.x branches. I have removed them from both branches, can you check this fixes the problem.

**Comment by matthewberryman** [comment]
Fixed in 6333573 and 3fb03ad
