### ISSUE TITLE
Bug (?) in boundary data

### ISSUE THREAD

**Issue by matthewberryman** [smart-facility/cognicity-schema#4]
I vaguely recall discussing this before. There's an area where you can put the mouse (OS X won't capture the mouse cursor so I've shown the approx. location with a star) and there's no real boundary (or a tiny one) associated with an area as shown. 
![screenshot 2015-11-18 15 07 49](https://cloud.githubusercontent.com/assets/2288238/11232373/6ad6c028-8e06-11e5-94ab-f39e84c27a44.png)

**Comment by talltom** [comment]
We should look at this when aggregates move to the analytics page.

**Comment by matthewberryman** [comment]
So the data is correct, it's just about representation?

**Comment by talltom** [comment]
sliver polygons are a function of digitisation errors and the spatial precision of the original data. Point is we don't know what boundaries to move to fix the input data so yes we're better of refining representation to improve user experience.
