### ISSUE TITLE
RAWA JATI region has different name in RW and Village tables

### ISSUE THREAD

**Issue by benatwork99** [smart-facility/cognicity-schema#6]
I occasionally see a JS error mousing over a particular area.

I think the cause is that the village name 'RAWA JATI' is in the RW table as 'RAWAJATI' which leads to a mismatch - this table row is never filled correctly, and looking at the DB I don't think the parent relationships were setup correctly for this village because of this mismatch.

**Comment by matthewberryman** [comment]
@marhardika which one is correct, 'RAWA JATI' or 'RAWAJATI'?

**Comment by mahardika** [comment]
it should be "RAWAJATI" @matthewberryman

**Comment by matthewberryman** [comment]
Thanks @mahardika.
@benatwork99 if you can please make the changes and then I can deploy them.

**Comment by benatwork99** [comment]
@matthewberryman There's only one change to this which you could do with an update statement. I'll write it for you now and post it as a comment. That'll save you updating whole tables.

**Comment by benatwork99** [comment]
UPDATE jkt_village_boundary
SET area_name = 'RAWAJATI',
 parent_name = 'PANCORAN'
WHERE area_name = 'RAWA JATI';

**Comment by matthewberryman** [comment]
@benatwork99 thanks for saving me the time of writing the SQL. 
@mahardika and @benatwork99 please check on the map on our sites.

**Comment by benatwork99** [comment]
FYI This is the region on the map:
![untitled2](https://cloud.githubusercontent.com/assets/970507/12838095/5d607286-cc1d-11e5-9e17-ef0511f56950.png)

**Comment by benatwork99** [comment]
On https://rem.petajakarta.org the region is working fine!

On https://petajakarta.org I can't see any regions and I get a console error about fetching the REM data at startup.

**Comment by benatwork99** [comment]
This region is working now as far as I can test on the deployed sites
